"""empty message

Revision ID: 6100b4720978
Revises: 69c2689b4e9a
Create Date: 2023-04-10 17:18:20.391405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6100b4720978'
down_revision = '69c2689b4e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userNumber', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_userNumber'), ['userNumber'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_userNumber'))
        batch_op.drop_column('userNumber')

    # ### end Alembic commands ###
